version: '3.8'
services:
  db:
    image: mysql
    restart: always
    env_file:
      - database.env
    ports:
      - '3306:3306'
    volumes:
      - db:/var/lib/mysql
  
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    env_file:
      - database_connect.env
    depends_on:
      - db
      
volumes:
  db:
    driver: local