# Generated by Django 3.2.7 on 2023-02-22 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rank_matrix', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='institute',
            name='available_branches',
            field=models.ManyToManyField(blank=True, default=None, related_name='Available_Branch', to='rank_matrix.Branch'),
        ),
    ]
