# Generated by Django 3.2.7 on 2024-01-08 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rank_matrix', '0002_auto_20230515_1315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institute',
            name='nirf_year',
            field=models.IntegerField(default=2024, null=True),
        ),
    ]
