# Generated by Django 3.2.7 on 2023-02-22 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rank_matrix', '0005_quota'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institute',
            name='available_categories',
            field=models.ManyToManyField(blank=True, default=None, related_name='Available_Categories', to='rank_matrix.Quota'),
        ),
    ]
