# Generated by Django 3.2.7 on 2022-12-19 07:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Round7',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quota', models.CharField(blank=True, max_length=100, null=True)),
                ('year', models.IntegerField(blank=True, null=True)),
                ('opening_rank', models.IntegerField(blank=True, null=True)),
                ('closing_rank', models.IntegerField(blank=True, null=True)),
                ('data_updated', models.BooleanField(default=False)),
                ('branch_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.branches')),
                ('category', models.ForeignKey(blank=True, max_length=100, null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.category')),
                ('institute_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.institutes')),
                ('seat_pool', models.ForeignKey(blank=True, max_length=100, null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.seat_pool')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Round6',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quota', models.CharField(blank=True, max_length=100, null=True)),
                ('year', models.IntegerField(blank=True, null=True)),
                ('opening_rank', models.IntegerField(blank=True, null=True)),
                ('closing_rank', models.IntegerField(blank=True, null=True)),
                ('data_updated', models.BooleanField(default=False)),
                ('branch_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.branches')),
                ('category', models.ForeignKey(blank=True, max_length=100, null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.category')),
                ('institute_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.institutes')),
                ('seat_pool', models.ForeignKey(blank=True, max_length=100, null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.seat_pool')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Round5',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quota', models.CharField(blank=True, max_length=100, null=True)),
                ('year', models.IntegerField(blank=True, null=True)),
                ('opening_rank', models.IntegerField(blank=True, null=True)),
                ('closing_rank', models.IntegerField(blank=True, null=True)),
                ('data_updated', models.BooleanField(default=False)),
                ('branch_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.branches')),
                ('category', models.ForeignKey(blank=True, max_length=100, null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.category')),
                ('institute_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.institutes')),
                ('seat_pool', models.ForeignKey(blank=True, max_length=100, null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.seat_pool')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Round4',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quota', models.CharField(blank=True, max_length=100, null=True)),
                ('year', models.IntegerField(blank=True, null=True)),
                ('opening_rank', models.IntegerField(blank=True, null=True)),
                ('closing_rank', models.IntegerField(blank=True, null=True)),
                ('data_updated', models.BooleanField(default=False)),
                ('branch_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.branches')),
                ('category', models.ForeignKey(blank=True, max_length=100, null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.category')),
                ('institute_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.institutes')),
                ('seat_pool', models.ForeignKey(blank=True, max_length=100, null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.seat_pool')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Round3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quota', models.CharField(blank=True, max_length=100, null=True)),
                ('year', models.IntegerField(blank=True, null=True)),
                ('opening_rank', models.IntegerField(blank=True, null=True)),
                ('closing_rank', models.IntegerField(blank=True, null=True)),
                ('data_updated', models.BooleanField(default=False)),
                ('branch_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.branches')),
                ('category', models.ForeignKey(blank=True, max_length=100, null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.category')),
                ('institute_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.institutes')),
                ('seat_pool', models.ForeignKey(blank=True, max_length=100, null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.seat_pool')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Round2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quota', models.CharField(blank=True, max_length=100, null=True)),
                ('year', models.IntegerField(blank=True, null=True)),
                ('opening_rank', models.IntegerField(blank=True, null=True)),
                ('closing_rank', models.IntegerField(blank=True, null=True)),
                ('data_updated', models.BooleanField(default=False)),
                ('branch_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.branches')),
                ('category', models.ForeignKey(blank=True, max_length=100, null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.category')),
                ('institute_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.institutes')),
                ('seat_pool', models.ForeignKey(blank=True, max_length=100, null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.seat_pool')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
