# Generated by Django 3.2.6 on 2021-09-11 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_alter_round_2015_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='round_2015',
            name='closing_rank',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='round_2015',
            name='opening_rank',
            field=models.IntegerField(null=True),
        ),
    ]
