# Generated by Django 3.2.7 on 2021-10-12 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_updates'),
    ]

    operations = [
        migrations.AlterField(
            model_name='updates',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
