# Generated by Django 3.2.6 on 2021-10-16 15:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_alter_updates_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='College_Branch',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('branch_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.branches')),
                ('institute_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.institutes')),
            ],
        ),
    ]
