# Generated by Django 3.2.6 on 2021-09-11 19:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_round1_2016_round2_2016_round3_2016_round4_2016_round5_2016_round6_2016'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Round3_2016',
            new_name='Round1_2017',
        ),
        migrations.RenameModel(
            old_name='Round2_2016',
            new_name='Round1_2018',
        ),
        migrations.RenameModel(
            old_name='Round5_2016',
            new_name='Round1_2019',
        ),
        migrations.RenameModel(
            old_name='Round4_2016',
            new_name='Round1_2020',
        ),
        migrations.CreateModel(
            name='Round7_2019',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('category', models.CharField(max_length=20)),
                ('opening_rank', models.IntegerField(null=True)),
                ('closing_rank', models.IntegerField(null=True)),
                ('branch_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.branches')),
                ('institute_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.institutes')),
            ],
        ),
        migrations.CreateModel(
            name='Round7_2018',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('category', models.CharField(max_length=20)),
                ('opening_rank', models.IntegerField(null=True)),
                ('closing_rank', models.IntegerField(null=True)),
                ('branch_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.branches')),
                ('institute_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.institutes')),
            ],
        ),
        migrations.CreateModel(
            name='Round7_2017',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('category', models.CharField(max_length=20)),
                ('opening_rank', models.IntegerField(null=True)),
                ('closing_rank', models.IntegerField(null=True)),
                ('branch_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.branches')),
                ('institute_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.institutes')),
            ],
        ),
        migrations.CreateModel(
            name='Round6_2020',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('category', models.CharField(max_length=20)),
                ('opening_rank', models.IntegerField(null=True)),
                ('closing_rank', models.IntegerField(null=True)),
                ('branch_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.branches')),
                ('institute_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.institutes')),
            ],
        ),
        migrations.CreateModel(
            name='Round5_2020',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('category', models.CharField(max_length=20)),
                ('opening_rank', models.IntegerField(null=True)),
                ('closing_rank', models.IntegerField(null=True)),
                ('branch_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.branches')),
                ('institute_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.institutes')),
            ],
        ),
        migrations.CreateModel(
            name='Round4_2020',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('category', models.CharField(max_length=20)),
                ('opening_rank', models.IntegerField(null=True)),
                ('closing_rank', models.IntegerField(null=True)),
                ('branch_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.branches')),
                ('institute_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.institutes')),
            ],
        ),
        migrations.CreateModel(
            name='Round3_2020',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('category', models.CharField(max_length=20)),
                ('opening_rank', models.IntegerField(null=True)),
                ('closing_rank', models.IntegerField(null=True)),
                ('branch_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.branches')),
                ('institute_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.institutes')),
            ],
        ),
        migrations.CreateModel(
            name='Round2_2020',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('category', models.CharField(max_length=20)),
                ('opening_rank', models.IntegerField(null=True)),
                ('closing_rank', models.IntegerField(null=True)),
                ('branch_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.branches')),
                ('institute_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.institutes')),
            ],
        ),
    ]
