# Generated by Django 3.2.6 on 2021-10-16 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_college_branch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='updates',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False),
        ),
    ]
