# Generated by Django 3.2.6 on 2021-10-16 15:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_alter_updates_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeatMatrix_2021I',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('quota', models.CharField(max_length=100, null=True)),
                ('category', models.CharField(max_length=100)),
                ('seat_pool', models.CharField(max_length=100, null=True)),
                ('seats', models.IntegerField(null=True)),
                ('branch_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.branches')),
                ('institute_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.institutes')),
            ],
        ),
        migrations.CreateModel(
            name='SeatMatrix_2021',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('quota', models.CharField(max_length=100, null=True)),
                ('category', models.CharField(max_length=100)),
                ('seat_pool', models.CharField(max_length=100, null=True)),
                ('seats', models.IntegerField(null=True)),
                ('branch_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.branches')),
                ('institute_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.institutes')),
            ],
        ),
    ]
