# Generated by Django 3.2.7 on 2021-10-26 18:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_seatmatrix_2021_seatmatrix_2021i'),
    ]

    operations = [
        migrations.AddField(
            model_name='college_branch',
            name='current',
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='seatmatrix_2021i',
            name='remark',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='Round6_2021',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('quota', models.CharField(max_length=100, null=True)),
                ('category', models.CharField(max_length=100)),
                ('seat_pool', models.CharField(max_length=100, null=True)),
                ('opening_rank', models.IntegerField(null=True)),
                ('closing_rank', models.IntegerField(null=True)),
                ('branch_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.branches')),
                ('institute_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.institutes')),
            ],
        ),
        migrations.CreateModel(
            name='Round5_2021',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('quota', models.CharField(max_length=100, null=True)),
                ('category', models.CharField(max_length=100)),
                ('seat_pool', models.CharField(max_length=100, null=True)),
                ('opening_rank', models.IntegerField(null=True)),
                ('closing_rank', models.IntegerField(null=True)),
                ('branch_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.branches')),
                ('institute_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.institutes')),
            ],
        ),
        migrations.CreateModel(
            name='Round4_2021',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('quota', models.CharField(max_length=100, null=True)),
                ('category', models.CharField(max_length=100)),
                ('seat_pool', models.CharField(max_length=100, null=True)),
                ('opening_rank', models.IntegerField(null=True)),
                ('closing_rank', models.IntegerField(null=True)),
                ('branch_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.branches')),
                ('institute_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.institutes')),
            ],
        ),
        migrations.CreateModel(
            name='Round3_2021',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('quota', models.CharField(max_length=100, null=True)),
                ('category', models.CharField(max_length=100)),
                ('seat_pool', models.CharField(max_length=100, null=True)),
                ('opening_rank', models.IntegerField(null=True)),
                ('closing_rank', models.IntegerField(null=True)),
                ('branch_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.branches')),
                ('institute_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.institutes')),
            ],
        ),
        migrations.CreateModel(
            name='Round2_2021',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('quota', models.CharField(max_length=100, null=True)),
                ('category', models.CharField(max_length=100)),
                ('seat_pool', models.CharField(max_length=100, null=True)),
                ('opening_rank', models.IntegerField(null=True)),
                ('closing_rank', models.IntegerField(null=True)),
                ('branch_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.branches')),
                ('institute_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.institutes')),
            ],
        ),
        migrations.CreateModel(
            name='Round1_2021',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('quota', models.CharField(max_length=100, null=True)),
                ('category', models.CharField(max_length=100)),
                ('seat_pool', models.CharField(max_length=100, null=True)),
                ('opening_rank', models.IntegerField(null=True)),
                ('closing_rank', models.IntegerField(null=True)),
                ('branch_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.branches')),
                ('institute_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.institutes')),
            ],
        ),
        migrations.CreateModel(
            name='College_category',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('category', models.CharField(max_length=5)),
                ('institute_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.institutes')),
            ],
        ),
    ]
