# Generated by Django 3.2.6 on 2021-09-28 17:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_auto_20210928_2014'),
    ]

    operations = [
        migrations.CreateModel(
            name='CSAB_2020_2',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('quota', models.CharField(max_length=100, null=True)),
                ('category', models.CharField(max_length=100)),
                ('seat_pool', models.CharField(max_length=100, null=True)),
                ('opening_rank', models.IntegerField(null=True)),
                ('closing_rank', models.IntegerField(null=True)),
                ('branch_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.branches')),
                ('institute_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.institutes')),
            ],
        ),
    ]
