# Generated by Django 3.2.6 on 2021-10-02 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0008_csab_2020_2'),
    ]

    operations = [
        migrations.AddField(
            model_name='branches',
            name='branch_code',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='branches',
            name='gfti',
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='branches',
            name='iiit',
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='branches',
            name='iit',
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='branches',
            name='nit',
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='institutes',
            name='city',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='institutes',
            name='state',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='institutes',
            name='website',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
