# Generated by Django 3.2.7 on 2022-06-10 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0008_auto_20220520_1718'),
    ]

    operations = [
        migrations.CreateModel(
            name='College_Type',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=10, verbose_name='College Type')),
            ],
        ),
    ]
