# Generated by Django 3.2.6 on 2021-10-02 06:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0009_auto_20211002_1111'),
    ]

    operations = [
        migrations.RenameField(
            model_name='branches',
            old_name='gfti',
            new_name='GFTI',
        ),
        migrations.RenameField(
            model_name='branches',
            old_name='iiit',
            new_name='IIIT',
        ),
        migrations.RenameField(
            model_name='branches',
            old_name='iit',
            new_name='IIT',
        ),
        migrations.RenameField(
            model_name='branches',
            old_name='nit',
            new_name='NIT',
        ),
    ]
