# Generated by Django 3.2.7 on 2022-06-27 18:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0009_college_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('album_name', models.CharField(max_length=100)),
                ('artist', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterModelOptions(
            name='institutes',
            options={'ordering': ['id']},
        ),
        migrations.AlterField(
            model_name='seatmatrix_2019',
            name='institute_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='institute_2019', to='backend.institutes'),
        ),
        migrations.AlterField(
            model_name='seatmatrix_2020',
            name='institute_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='institute_2020', to='backend.institutes'),
        ),
        migrations.AlterField(
            model_name='seatmatrix_2020_csab',
            name='institute_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='institute_2020_CSAB', to='backend.institutes'),
        ),
        migrations.AlterField(
            model_name='seatmatrix_2021',
            name='institute_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='institute', to='backend.institutes'),
        ),
        migrations.AlterField(
            model_name='seatmatrix_2021i',
            name='institute_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='institute_2021', to='backend.institutes'),
        ),
        migrations.AlterUniqueTogether(
            name='institutes',
            unique_together={('name', 'id')},
        ),
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField()),
                ('title', models.CharField(max_length=100)),
                ('duration', models.IntegerField()),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracks', to='backend.album')),
            ],
            options={
                'ordering': ['order'],
                'unique_together': {('album', 'order')},
            },
        ),
    ]
