# Generated by Django 3.2.6 on 2021-10-02 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0010_auto_20211002_1158'),
    ]

    operations = [
        migrations.AddField(
            model_name='institutes',
            name='address',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='institutes',
            name='display_code',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='institutes',
            name='email',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='institutes',
            name='fax',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='institutes',
            name='nirf_19',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='institutes',
            name='nirf_20',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='institutes',
            name='nirf_21',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='institutes',
            name='phone',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
