# Generated by Django 3.2.7 on 2022-06-27 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0011_alter_track_album'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='seatmatrix_2021',
            options={'ordering': ['id']},
        ),
        migrations.AlterUniqueTogether(
            name='seatmatrix_2021',
            unique_together={('institute_code', 'id')},
        ),
    ]
