# Generated by Django 3.2.6 on 2021-10-02 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0011_auto_20211002_2058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institutes',
            name='nirf_19',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='institutes',
            name='nirf_20',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='institutes',
            name='nirf_21',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
