# Generated by Django 3.2.6 on 2021-10-03 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0013_alter_institutes_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='institutes',
            name='current',
            field=models.CharField(max_length=2, null=True),
        ),
    ]
