# Generated by Django 3.2.7 on 2023-05-15 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rank_matrix_stage', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='college_quota',
            name='institute_code',
        ),
        migrations.DeleteModel(
            name='College_Branch',
        ),
        migrations.DeleteModel(
            name='College_Quota',
        ),
    ]
